### ISSUE TITLE
How to turn off completely the modem

### ISSUE THREAD

**Issue by freeasabeer** [Xinyuan-LilyGO/T-A7608X#10]
In [TinyGSM_Net_GNSS.ino](https://github.com/Xinyuan-LilyGO/T-A7608X/blob/main/examples/Arduino/TinyGSM_Net_GNSS/TinyGSM_Net_GNSS.ino)
we can find the following to power off the modem:
```
    // Try to power-off (modem may decide to restart automatically)
    // To turn off modem completely, please use Reset/Enable pins
    modem.poweroff();
```

What is the sequence of Reset/Enable pins to completely turn off the modem ?

**Comment by LilyGO** [comment]
Hello. IO12 can control the power supply of A7608 when using battery power only.
