### ISSUE TITLE
Low download speed on any type of connection

### ISSUE THREAD

**Issue by emil151997** [Xinyuan-LilyGO/T-A7608X#13]
Hello!
I am using the board LILYGO T-A7608E-H. And i Have an issue. I have configured the SIM module for 921600 baud speed (with AT command). But when i try different modes (automatic, LTE, WCDMA, 2G) i always have the same low speed (around 5-6 Kbyte/s), when downloading files. I am using TinyGsm library and FileDownload Example.

**Comment by emil151997** [comment]
Hello again! 
So i solved the issue, just by using AT HTTP Comands (AT+HTTPINIT ... etc). This commands are listed in file below
[A7600_Series_AT_Command_Manual_V1.02.pdf](https://github.com/Xinyuan-LilyGO/T-A7608X/files/11772214/A7600_Series_AT_Command_Manual_V1.02.pdf)

**Comment by gasagna** [comment]
Hi @emil151997, if you want to use the native http client provided by the a7608 module, check out this [library](https://github.com/gasagna/A76XX) I made specifically for this board. Happy to support you, if you need help with it.
