### ISSUE TITLE
Can't flash the LILYGO T-A7608E-H board

### ISSUE THREAD

**Issue by matthieu-sofa** [Xinyuan-LilyGO/T-A7608X#3]
Hi here, 

I ordered some LILYGO T-A7608E-H boards for a side project but I'm not able to flash the firmware on them. 

I'm receiving the following error via ArduinoIDE:
`Sketch uses 296122 bytes (22%) of program storage space. Maximum is 1310720 bytes.
Global variables use 14308 bytes (4%) of dynamic memory, leaving 313372 bytes for local variables. Maximum is 327680 bytes.
esptool.py v3.0-dev
Serial port /dev/cu.usbmodem54D80012771
Connecting......
Chip is ESP32-D0WD-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 94:e6:86:a6:9b:b0
Uploading stub...

A fatal error occurred: Failed to write to target RAM (result was 01070000)
A fatal error occurred: Failed to write to target RAM (result was 01070000)`

Do you know if there is a specific procedure to have the board enter the flashing mode? I previously used the Lilygo SIM800L and never had issue. 

Here are my settings:
My board is connected via USB-C to my Mac

![CleanShot 2022-09-08 at 22 16 49](https://user-images.githubusercontent.com/61499917/189217564-a9d8eb60-d6b3-4200-8315-340e281512b8.png)

![CleanShot 2022-09-08 at 22 18 06](https://user-images.githubusercontent.com/61499917/189217689-c07888e6-8280-4011-8eb9-8185cfe900d0.png)

The file I'm trying is the one we can find on this repo: https://github.com/Xinyuan-LilyGO/T-A7608X/blob/main/examples/Arduino/HttpsClient/HttpsClient.ino

Thanks a lot for your help.

**Comment by LilyGO** [comment]
reference： https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/issues/139
