### ISSUE TITLE
Missing documentation on charge controller on this board.

### ISSUE THREAD

**Issue by gasagna** [Xinyuan-LilyGO/T-A7608X#4]
As the title says, it is unclear if the board is equipped with a solar charge controller device. 

Clarifying this information in the main page would help.

Thanks.

**Comment by LilyGO** [comment]
Hello，Support solar energy. Details are provided under the Purchase link
![1](https://user-images.githubusercontent.com/31160602/191147322-f4014733-4185-4e7e-8065-3d794180909f.png)

**Comment by gasagna** [comment]
Hi, 

I might not have been very clear, sorry. 

I have seen there is a connector to attach a solar panel, but what is not clear is if the board has a chip to manage the charge from the solar panel to the battery.

A similar [board](https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G) has a CN3065 chip for solar charge input management, but there is nothing available in the docs for the T-A7608X board.

Thanks

**Comment by LilyGO** [comment]
Yes. T-A7608 has CN3065 on board
