### ISSUE TITLE
What type of JST connector for the solar charge does this board have?

### ISSUE THREAD

**Issue by gasagna** [Xinyuan-LilyGO/T-A7608X#5]
Hi, 

can you confirm this board has a  JST PH 2-Pin connector for the solar charge? That's what it looks like.

Thanks

**Comment by LilyGO** [comment]
Hello. Is that what you're talking about?
![1](https://user-images.githubusercontent.com/31160602/191880367-cf6ac271-594d-4e60-8a5f-14e3427c1034.png)

**Comment by gasagna** [comment]
Yes, I was wondering what type of jst connector that is. Thanks.

**Comment by LilyGO** [comment]
2.0
