### ISSUE TITLE
Missing info on LEDs function

### ISSUE THREAD

**Issue by gasagna** [Xinyuan-LilyGO/T-A7608X#6]
Hi, 

this repo is missing some docs on the function of the LED on this board. For instance, what is the purpose of the two red LEDs next to the GSM antenna attachment point?

Thanks

**Comment by LilyGO** [comment]
Hello, one is the power indicator for the A7608. One is the network status indicator.

**Comment by gasagna** [comment]
Great and what is the blue LED for? can it be controlled programmatically?

**Comment by LilyGO** [comment]
The blue LED light is the charging indicator. Not programming
